-- AlterTable
ALTER TABLE "whatsapp_templates" ADD COLUMN     "category" TEXT NOT NULL DEFAULT 'UTILITY',
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "footerText" TEXT,
ADD COLUMN     "metaId" TEXT,
ADD COLUMN     "rejectedReason" TEXT,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'APPROVED',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
