-- AlterTable
ALTER TABLE "User" ALTER COLUMN "cpf" DROP NOT NULL,
ALTER COLUMN "data_nasc" DROP NOT NULL,
ALTER COLUMN "rua" DROP NOT NULL,
ALTER COLUMN "bairro" DROP NOT NULL,
ALTER COLUMN "numero" DROP NOT NULL,
ALTER COLUMN "cep" DROP NOT NULL;
